### Option: Plugins.KeaDHCP.System.Path
#	Specifies the path for the binary of the plugin
#
# Mandatory: yes
# Default:

Plugins.KeaDHCP.System.Path=/usr/libexec/zabbix/zabbix-agent2-plugin-keadhcp

### Option: Plugins.KeaDHCP.Sessions.*
#	Socket path to be used for connection. "*" should be replaced with a session name.
#
# Mandatory: no
# Default:
# Plugins.KeaDHCP.Sessions.*=

Plugins.KeaDHCP.Sessions.dhcp4.Uri=unix:///run/kea/kea4-ctrl-socket
Plugins.KeaDHCP.Sessions.dhcp6.Uri=unix:///run/kea/kea6-ctrl-socket